export default {
  background: { "sike there's no background": 888 },
  outline: {
    brown: 80,
    green: 87,
    black: 360,
    red: 75,
    purple: 94,
    pink: 83,
    "midnight blue": 109,
  },
  face: {
    "happy dark grey face": 23,
    "happy yellow face": 19,
    "happy red face": 25,
    "neutral red face": 24,
    "happy grey face": 27,
    "neutral white face": 25,
    "sad dark green face": 28,
    "sad pink face": 19,
    "happy white face": 23,
    "sad teal face": 25,
    "neutral blue face": 19,
    "neutral dark grey face": 20,
    "neutral dark green face": 19,
    "sad green face": 24,
    "happy dark green face": 21,
    "happy blue face": 26,
    "neutral grey face": 19,
    "happy orange face": 24,
    "neutral dark blue face": 19,
    "neutral brown face": 21,
    "happy teal face": 19,
    "sad brown face": 22,
    "neutral yellow face": 30,
    "happy dark blue face": 18,
    "sad yellow face": 22,
    "neutral purple face": 12,
    "neutral pink face": 19,
    "sad white face": 18,
    "sad orange face": 23,
    "sad blue face": 19,
    "sad grey face": 16,
    "sad dark grey face": 15,
    "sad purple face": 15,
    "sad dark blue face": 21,
    "neutral green face": 26,
    "happy purple face": 26,
    "happy brown face": 22,
    "neutral orange face": 19,
    "happy pink face": 15,
    "neutral teal face": 21,
    "sad red face": 24,
    "happy green face": 16,
  },
  hoodie: {
    "dark grey hoodie ": 56,
    "pink hoodie ": 56,
    "rainbow hoodie ": 16,
    "grey hoodie ": 55,
    "red hoodie ": 61,
    "orange hoodie ": 58,
    "blue hoodie ": 51,
    "dark blue hoodie ": 61,
    "purple hoodie ": 54,
    "yellow hoodie ": 58,
    "teal hoodie ": 58,
    "wizard hoodie ": 10,
    "cloudy hoodie ": 8,
    "brown hoodie ": 51,
    "dark green hoodie ": 49,
    "green hoodie ": 58,
    "white hoodie ": 45,
    "tie dye hoodie ": 14,
    "love hoodie ": 17,
    "chain and hoodie ": 10,
    "clown hoodie ": 18,
    "camo hoodie ": 16,
    "peach hoodie ": 4,
    "midnight hoodie ": 4,
  },
};
